main.c File Reference
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <assert.h>
Classes
struct solution
Struct that stores solutions.
struct quadraticEquation
Struct that stores coeffs and answers of quadratic equation.
Macros
#define EXIT_BAD_INPUT 1
Typedefs
typedef struct solution solution_t
Struct that stores solutions.
typedef struct quadraticEquation quadraticEquation_t
Struct that stores coeffs and answers of quadratic equation.
Enumerations
enum solutionCode {
ZERO_ROOTS
, ONE_ROOT
, TWO_ROOTS
, INF_ROOTS
,
BLANK_ROOT = -1
 }
Exit codes used in solution_t struct.
Functions
void printKvadr (quadraticEquation_t *equation)
Prints quadratic equation in nice format.
double fixMinusZero (double num)
Fixes -0.
quadraticEquation_t * solveQuadratic (quadraticEquation_t *equation)
solves equation, prints some comments and returns struct with answers
int scanCoefficients (quadraticEquation_t *equation, int argc, char *argv[])
Scans coeffs of quadratic eqaution from cmd args (if possible) or from console input.
void printAnswer (quadraticEquation_t *equation)
Prints roots of solved equation.
int main (int argc, char *argv[])
Variables
const double EPSILON = 1e-10
const solution_t BLANK_SOLUTION = {BLANK_ROOT, NAN, NAN}
Detailed Description
Program for solving quadratic equation
Definition in file main.c.
Macro Definition Documentation
EXIT_BAD_INPUT
#define EXIT_BAD_INPUT 1
Definition at line 10 of file main.c.
Referenced by main().
Typedef Documentation
quadraticEquation_t
typedef struct quadraticEquation quadraticEquation_t
Struct that stores coeffs and answers of quadratic equation.
solution_t
typedef struct solution solution_t
Struct that stores solutions.
Enumeration Type Documentation
solutionCode
enum solutionCode
Exit codes used in solution_t struct.
See also
solution
Enumerator
ZERO_ROOTS 0 roots
ONE_ROOT 1 root
TWO_ROOTS 2 roots
INF_ROOTS infinity roots, 0 = 0
BLANK_ROOT This code is used when solution_t is initialized.
Definition at line 15 of file main.c.
                  {
    ZERO_ROOTS,
    ONE_ROOT,
    TWO_ROOTS,
    INF_ROOTS,
    BLANK_ROOT = -1
};
Function Documentation
fixMinusZero()
double fixMinusZero (double num)
Fixes -0.
Parameters
 in num Number to fix
Returns
Fixed number
Definition at line 237 of file main.c.
                                {
    return (fabs(num) < EPSILON) ? fabs(num) : num;
}
References EPSILON.
Referenced by solveQuadratic().
main()
int main (int argc, char * argv[])
Definition at line 105 of file main.c.
                                 {
    printf("# Quadratic equation solver\n# orientiered 2024\n");
    quadraticEquation_t equation = {.0, .0, .0, BLANK_SOLUTION};
    if (!scanCoefficients(&equation, argc, argv)) {
        printf("Wrong input format\n");
        exit(EXIT_BAD_INPUT);
    }
    printKvadr(&equation);
    solveQuadratic(&equation);
    printAnswer(&equation);
    return 0;
}
References BLANK_SOLUTION, EXIT_BAD_INPUT, printAnswer(), printKvadr(), scanCoefficients(), and solveQuadratic().
printAnswer()
void printAnswer (quadraticEquation_t * equation)
Prints roots of solved equation.
Parameters
 in equation Pointer to struct that holds coeffs and answers
Definition at line 170 of file main.c.
                                                {
    switch(equation->answer.code) {
        case BLANK_ROOT:
            printf("Something went wrong\n");
            break;
        case ZERO_ROOTS:
            break;
        case ONE_ROOT:
            printf("x = %lg\n", equation->answer.x1);
            break;
        case TWO_ROOTS:
            printf("x1 = %lg\nx2 = %lg\n", equation->answer.x1, equation->answer.x2);
            break;
        case INF_ROOTS:
            printf("x is any number");
            break;
        default:
            printf("That's really bad :(\n");
            break;
    }
}
References quadraticEquation::answer, BLANK_ROOT, solution::code, INF_ROOTS, ONE_ROOT, TWO_ROOTS, solution::x1, solution::x2, and ZERO_ROOTS.
Referenced by main().
printKvadr()
void printKvadr (quadraticEquation_t * equation)
Prints quadratic equation in nice format.
Parameters
 in equation Pointer to struct with coeffs
Returns
Nothing
Skips zero-coefs, and doesn't print 1 Example: 0 1 -5 => x - 5 = 0
Definition at line 139 of file main.c.
                                               {
    int printedBefore = 0; //remembering if we printed something to put signs correctly
    double a = equation->a,
            b = equation->b,
            c = equation->c;
    if (fabs(a) > EPSILON) { //if not zero
        if (a < 0) printf("-"); //sign
        if (fabs(fabs(a)-1) > EPSILON) printf("%g", fabs(a)); //1x^2 is the same as x^2
        printf("x^2 ");
        printedBefore = 1;
    }
    if (fabs(b) > EPSILON) {
        if (printedBefore) printf((b < 0) ? "- " : "+ ");
        if (fabs(fabs(b)-1) > EPSILON) printf("%g", printedBefore ? fabs(b) : b);
        //if a == 0 => we should print -b, not "- b"
        printf("x ");
        printedBefore = 1;
    }
    if (!(printedBefore && fabs(c) < EPSILON)) { //x + 0 <=> x
        if (printedBefore) printf((c < 0) ? "- %g " : "+ %g ", fabs(c));
        else printf("%g ", c);
    }
    printf("= 0\n");
}
References quadraticEquation::a, quadraticEquation::b, quadraticEquation::c, and EPSILON.
Referenced by main().
scanCoefficients()
int scanCoefficients (quadraticEquation_t * equation, int argc, char * argv[])
Scans coeffs of quadratic eqaution from cmd args (if possible) or from console input.
Parameters
 in,out equation Pointer to struct that holds coeffs and answers
 in argc Number of cmd arguments
 in argv Cmd arguments
Returns
0 if problem occured, 1 if input is readed correctly
Definition at line 124 of file main.c.
                                                                           {
    if (argc != 4)
        printf("Enter coefficients of equation ax^2 + bx + c = 0\n");
    if (argc == 4) { //getting input from cmd args
        equation->a = atof(*++argv);
        equation->b = atof(*++argv);
        equation->c = atof(*++argv);
    } else if (scanf("%lf %lf %lf", &(equation->a), &(equation->b), &(equation->c)) != 3) { //getting input from user
        return 0;
    }
    return 1;
}
References quadraticEquation::a, quadraticEquation::b, and quadraticEquation::c.
Referenced by main().
solveQuadratic()
quadraticEquation_t * solveQuadratic (quadraticEquation_t * equation)
solves equation, prints some comments and returns struct with answers
Parameters
 in,out equation Pointer to struct that holds coeffs and answers
Returns
solution_t pointer to struct with roots and exit code
Solves quadratic equation in form ax^2 + bx + c = 0 Prints comments, if there aren't any roots. Also fixes -0 in answer
Definition at line 193 of file main.c.
                                                                   {
    double a = equation->a,
            b = equation->b,
            c = equation->c;
    assert(isfinite(a)); //checking input for NaNs
    assert(isfinite(b));
    assert(isfinite(c));
    if (fabs(a) < EPSILON) { //checking for zeros in coefficients; we divide only by a, so this check is essential
        //a = 0
        if (fabs(b) < EPSILON) {
            //b = 0
            if (fabs(c) < EPSILON) { // 0 = 0
                equation->answer.code = INF_ROOTS;
            } else {
                printf("Equation can't be solved\n");
                equation->answer.code = ZERO_ROOTS;
            }
        } else {
            equation->answer.code = ONE_ROOT;
            equation->answer.x1 = -c/b;
        }
    } else {
        double D = b*b - 4*a*c; //calculating discriminant
        if (fabs(D) < EPSILON) { //D = 0
            equation->answer.code = ONE_ROOT;
            equation->answer.x1 = -b / (2*a);
        } else if (D < 0) {
            equation->answer.code = ZERO_ROOTS; //D < 0
            printf("Equation can't be solved in R: D = %g < 0\n", D);
        } else { //D > 0
            equation->answer.code = TWO_ROOTS;
            double D_sqrt = sqrt(D);
            equation->answer.x1 = (-b + D_sqrt)/(2*a);
            equation->answer.x2 = (-b - D_sqrt)/(2*a);
        }
    }
    //fix -0 case
    equation->answer.x1 = fixMinusZero(equation->answer.x1);
    equation->answer.x2 = fixMinusZero(equation->answer.x2);
    return equation;
}
References quadraticEquation::a, quadraticEquation::answer, quadraticEquation::b, quadraticEquation::c, solution::code, EPSILON, fixMinusZero(), INF_ROOTS, ONE_ROOT, TWO_ROOTS, solution::x1, solution::x2, and ZERO_ROOTS.
Referenced by main().
Variable Documentation
BLANK_SOLUTION
const solution_t BLANK_SOLUTION = {BLANK_ROOT, NAN, NAN}
Definition at line 33 of file main.c.
{BLANK_ROOT, NAN, NAN};
Referenced by main().
EPSILON
const double EPSILON = 1e-10
Definition at line 9 of file main.c.
Referenced by fixMinusZero(), printKvadr(), and solveQuadratic().